---
document_title: Milton Stats
club_of_interest: "4363"
club_name: "Milton CC"
year_of_interest: 2025
start_year: 2005
default_list_length: 12
short_list_length: 6
qualify_balls_faced: 300
qualify_balls_bowled: 300
qualify_inns_avgs: 5
qualify_wkts_taken: 10

opponents_of_interest: 
# - 4363 # Milton
# - 14848 #CUPA
# - 12697 # Reach
# - 8183 # Cambourne
 - 1771 # Chatteris
# - 23328 # Northstowe
# - 4096 # Longstanton GH
# - 831 # Audley End

player_to_plot: 
  - 1878269 #day
  - 3682607 #day
  - 3716426 #day
  - 4453764 #day
 # - 4203792 #sivvers
 # - 5490886 #jupp
 # - 3945561
 # - 3827941

our_teams_names:
    9865: "1st XI"
    9866: "2nd XI"
    9867: "3rd XI"
    161677: "Midweek"
    9868: "Friendly"
    #162507: "Friendly 2"
    #198440: "Beehive"
    #338975: "Midweek XI"# a duplicate? never used
    
home_ground_names:
   51122: "NLP"
   12581: "Sycamores"
 
leagues_of_interest:
 - 269 # "Cambridgeshire & Huntingdonshire Premier League"
 - 10270 # "Cambridge Business House League" 15 * 8 ball overs
 - 270 # "Cambridgeshire Cricket Association"
 - 7387 # "National Village Cup", which is 40 oves
#- 25572 # 'University of Cambridge Inter Department Cricket League' 

#use this to exclude youth sides:
excluded_teams:
 - 9872 #colts
 - 82246 # u10
 - 9871 # u11
 - 82254 # u12
 - 9870 # u13
 - 134986 # another u13?
 - 9869 # u14
 - 24125 # u15
 
excluded_leagues:
 - 7321 # "Cambridgeshire Youth Cricket Association"
 - 357 # 'Ipswich and District Youth League'
 - 10172 # 'ECB U15 Club T20'
 - 467 # Pontefract, spurious overs? 
 - 389 # Suffolk, only one youth match in set 

# spurious matches -- found by unusual dismissals, initially
excluded_matches:
 - 4735382
 - 4735364
 - 4735216
 - 4735198
 - 4735186
 - 4735183
 - 4735132
 - 4735129
 - 4735120
 - 4735102
 - 4510987
 - 4511037
 - 4512821
 - 4512829
 - 4512934
 - 4512958
 - 6592481 # dodgy March duplicate
 - 7125221 # dodgy duplicate
 - 3211535 # this is nearly complete but still four hit ball twice
 - 515424 # duplicate batter
 - 440098 # duplicate batter
 - 1002432 # a youth match unique in its competition, no data
 - 490642 # badly incomplete and not interesting
 # - 3933689 # a lot of missing data in this, but just about useful
---
